import { sunRadius } from "../Experience/solarSystem/Sun";

export default [
  {
    name: "mercury",
    radius: 0.03,
    distance: 7.5 + sunRadius,
    orbitSpeed: 1.6,
    rotationSpeed: 0.016,
    texture: "./textures/mercury.webp",
  },
  {
    name: "venus",
    radius: 0.095,
    distance: 15 + sunRadius,
    orbitSpeed: 1.17,
    rotationSpeed: 0.004,
    texture: "./textures/venus/venus.webp",
    atmosphereTexture: "./textures/venus/venus_atmosphere.webp",
  },
  {
    name: "earth",
    radius: 0.1,
    distance: 22.5 + sunRadius,
    orbitSpeed: 1,
    rotationSpeed: 1,
    textures: {
      day: "./textures/earth/day.webp",
      night: "./textures/earth/night.webp",
      specularClouds: "./textures/earth/specularClouds.webp",
    },
    moon: {
      radius: 0.027,
      distance: 0.3,
      orbitSpeed: 0.5,
      rotationSpeed: 1,
      texture: "./textures/moon.webp",
    },
  },
  {
    name: "mars",
    radius: 0.053,
    distance: 33 + sunRadius,
    orbitSpeed: 0.8,
    rotationSpeed: 1.03,
    texture: "./textures/mars.webp",
  },
  {
    name: "jupiter",
    radius: 1.12,
    distance: 78 + sunRadius,
    orbitSpeed: 0.43,
    rotationSpeed: 2.4,
    texture: "./textures/jupiter.webp",
  },
  {
    name: "saturn",
    radius: 0.945,
    distance: 142.5 + sunRadius,
    orbitSpeed: 0.32,
    rotationSpeed: 2.3,
    texture: "./textures/saturn/saturn.webp",
    hasRings: true,
    ringTexture: "./textures/saturn/saturn_ring.png",
  },
  {
    name: "uranus",
    radius: 0.4,
    distance: 288 + sunRadius,
    orbitSpeed: 0.23,
    rotationSpeed: 1.4,
    texture: "./textures/uranus.webp",
  },
  {
    name: "neptune",
    radius: 0.39,
    distance: 450 + sunRadius,
    orbitSpeed: 0.18,
    rotationSpeed: 1.5,
    texture: "./textures/neptune.webp",
  },
];
